### ISSUE TITLE
Optimize loading time

### ISSUE THREAD

**Issue by IEVin** [maraf/GitExtensions.SolutionRunner#11]
The loading time can be quite long for a large project (~2-3 sec). To reduce this I suggest:

1. Use git index instead of directy searching for _sln_ files in file system. 
For example: `git ls-files -cmo | grep \.sln$` or filter this on C# code.

2. Cache the previous result and update it in the background.

**Comment by maraf** [comment]
Sounds good to me 👍 Are you interested in submitting a PR?

> 1. Use git index instead of directy searching for _sln_ files in file system.
>    For example: `git ls-files -cmo | grep \.sln$` or filter this on C# code.

Currently, there is the option to scan the root directory only, but you are right that the full search can use git index.

> 2. Cache the previous result and update it in the background.

As this cache must be per-repository, where to store it?

**Comment by IEVin** [comment]
> Are you interested in submitting a PR?

I submitted it. 

>As this cache must be per-repository, where to store it?

GE used AppData\Roaming for this purpose.

 One text file named by repo stored in Users\<CurrentUser>\AppData\Roaming\GitExtensions\Plugins\SolutionRunner\cache\ or something like this. 

This may be actual only for large repopositories with many small files.

P.S.: After GitExtensions.Extensibility was updated to 0.1.1.40 build broken. Now GE unpack dir is _gitextensions.shared_ (before was _references_).

**Comment by maraf** [comment]
> GE used AppData\Roaming for this purpose.

Ok, you are right.



> P.S.: After GitExtensions.Extensibility was updated to 0.1.1.40 build broken. Now GE unpack dir is _gitextensions.shared_ (before was _references_).

There is a MSBuild property `GitExtensionsDownloadPath` for this.
