### ISSUE TITLE
Feature Request: VSCode workspaces

### ISSUE THREAD

**Issue by MISTikus** [maraf/GitExtensions.SolutionRunner#20]
It would be great if this plugin also could run `*.code-workspace` files using VSCode (or default program), maybe optional, according plugin settings...
This files are VSCode solution analogue.

For now, I'm using hotkey `Ctrl+O` to open this files, but to open i has to locate file manually...

*I've created PR: #21

**Comment by maraf** [comment]
@MISTikus The feature is up on nuget in v4.2.0. Thank you!
