### ISSUE TITLE
Crash on GitEx v3.5

### ISSUE THREAD

**Issue by MISTikus** [maraf/GitExtensions.SolutionRunner#23]
After update to GitExtensions v3.5, hover on SolutionRunner menu crashes the app.

**Comment by MISTikus** [comment]
i guess it crashes because of GitEx cannot find BugReporter, but i think SolutionRunner is producing an error...

**Comment by maraf** [comment]
Thanks for the report. There is a change in the method `IExecutable.Start`. It is compatible on source level, but not on binary. The fix is to rebuild Solution Runner with reference to Git Extensions v3.5. I will do it and publish the plugin on nuget once GE v3.5 is released.

**Comment by MISTikus** [comment]
thanks! it works)
