### ISSUE TITLE
Feature Request: Run as Administrator

### ISSUE THREAD

**Issue by mlafleur** [maraf/GitExtensions.SolutionRunner#25]
There are cases where a Solution must be opened as an Administrator in order to debug. 
Examples include Projects that require Azure Service Fabric or Azure Storage/Compute Emulator.

**Comment by maraf** [comment]
Thanks for the suggestion. Do you have any idea how to execute such action? 
In desktop version of Solution Runner, these are available as "access key extensions", but I don't have any good idea how to add such functionality to the menu of Git Extensions.

![image](https://user-images.githubusercontent.com/10020471/116596963-56cb9a00-a925-11eb-83cf-2ef35d2c7c29.png)
