### ISSUE TITLE
Plugin not working - Error in newest GitExtension Version (v4) 

### ISSUE THREAD

**Issue by AngieKadnar** [maraf/GitExtensions.SolutionRunner#28]
I installed the latest version of GitExtension yesterday (V4). Unfortunately an error is thrown as soon as I clicked the dropdown from SolutionRunner Plugin.

**Installed GitExtension Version:**
https://github.com/gitextensions/gitextensions/releases/tag/v4

**Error Scenario:**
![SolutionRunner_GitExtensionV4_Error](https://user-images.githubusercontent.com/45826225/199680368-cbed29d9-0176-434e-9d9a-cfb355a820bf.gif)

**Error Detail:**
> - Git Extensions 4.0.0.15569
> - Build cba315df5366fca01240d93b6e5a5077fd5e6630
> - Git 2.38.1.windows.1
> - Microsoft Windows NT 10.0.19042.0
> - .NET 6.0.10
> - DPI 96dpi (no scaling)
> ```
> System.MissingMethodException: Method not found: '!!0 GitUIPluginInterfaces.ISettingsSource.GetValue(System.String, !!0, System.Func`2<System.String,!!0>)'.
>    at GitExtensions.SolutionRunner.PluginSettings.get_IsTopLevelSearchedOnly()
>    at GitExtensions.SolutionRunner.UI.SolutionListMenuItem.OnDropDownOpening(Object sender, EventArgs e) in D:\Development\Maraf\GitExtensions.SolutionRunner\src\GitExtensions.SolutionRunner\UI\SolutionListMenuItem.cs:line 40
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
> ```

![image](https://user-images.githubusercontent.com/45826225/199679597-efd55509-fd9b-4b57-afeb-aa74cfc24f4f.png)
![image](https://user-images.githubusercontent.com/45826225/199694213-d5175bae-10dd-4f8b-86c9-41626a366efd.png)
![image](https://user-images.githubusercontent.com/45826225/199694231-bf03b0fc-5e2b-48bd-93e5-3c797c7a49b5.png)

**Comment by maraf** [comment]
Yeah, this is a known problem in Git Extensions plugins. As there isn't a supported API, most of the plugins are "hacks" and sometimes they broke between Git Extensions releases.

Probably all that is needed is to update [Git Extensions reference version in the csproj](https://github.com/maraf/GitExtensions.SolutionRunner/blob/master/src/GitExtensions.SolutionRunner/GitExtensions.SolutionRunner.csproj#L44) and rebuild the plugin.

PR welcomed.
