### ISSUE TITLE
Wrong dependencies in metadata (GitExtensions.Extensibility => Version="0.3.*" missing)

### ISSUE THREAD

**Issue by AngieKadnar** [maraf/GitExtensions.SolutionRunner#31]
The dependencies are not up to date. It seems that this was forgotten to update during the last update.
I think this is the reason why the plugin is not found in the PluginManager of the current version of GitExtensions.
GitExtensions.Extensibility has been updated to version 0.3 in the last update.

![image](https://user-images.githubusercontent.com/45826225/205024892-b0ab23a5-ca87-47ea-8939-5a2231fb0815.png)

![image](https://user-images.githubusercontent.com/45826225/205022825-4580433b-29db-4726-8dda-9bfef879b388.png)

**Comment by maraf** [comment]
Please, send me "Startup arguments" from Plugin Manager log 
![image](https://user-images.githubusercontent.com/10020471/205049798-6fbf8c4d-5ade-494a-aff8-8cfe4600882f.png)

**Comment by AngieKadnar** [comment]
Here are my startup arguments:

--path C:\Users\akd\AppData\Local\GitExtensions\UserPlugins --monikers net5.0,any,netstandard2.0 --dependencies GitExtensions.Extensibility-v0.2.0 --tags GitExtensions --selfpackageid GitExtensions.PluginManager --processnamestokillbeforechange GitExtensions

**Comment by maraf** [comment]
Thanks! I have opened the PR to fix this. Unfortunatelly the plugin won't be visible util https://github.com/gitextensions/gitextensions.pluginmanager/pull/68 is merged and propagated to Git Extensions, probably in 4.0.1
