### ISSUE TITLE
SolutionRunner no longer works with GitExtensions 5.0.0

### ISSUE THREAD

**Issue by rizi** [maraf/GitExtensions.SolutionRunner#40]
After updating GE to 5.0.0 SolutionRunner no longer works, it's still installed but it no longer shows the SolutionRunner Menu.

It would be great if a new version can fix this.

Br

**Update 2024-09-10**
#41 should fix this issue.

**Comment by MISTikus** [comment]
Maybe we should bring @maraf's attention to this issue?
